version: '3.7'

services:

  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - .volumes/mongo:/data/db
    env_file:
      - .env
    expose:
      - 27017

  app:
    image: diraven/crabot:latest
    depends_on:
      - mongo
    restart: always
    env_file:
      - .env
