version: '3.7'

services:

  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 80:8081
    env_file:
      - .env

  app:
    build: app
    restart: "no"
    volumes:
      - ./app:/app
