version: '3.3'

services:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 80:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: crabot
      ME_CONFIG_MONGODB_ADMINPASSWORD: JPX9Qppx9XDKrXRbNFaq3imVVNxQWV6

  app:
    build: app
